import { NextRequest, NextResponse } from "next/server";
import { withFrontendOriginGate } from "@/lib/server/frontendRequestGuard";

const SUPPORTED_CHAINS = [
  {
    chainId: "5042002",
    numericId: 5042002,
    name: "Arc Testnet",
    key: "arc-testnet",
    type: "evm",
    nativeCurrency: { name: "USD Coin", symbol: "USDC", decimals: 18 },
    rpcUrl: "https://rpc.testnet.arc.network",
    explorerUrl: "https://testnet.arcscan.app",
    supportedFeatures: ["swaps", "bridge", "rpc-proxy", "wallet-balance"],
  },
  {
    chainId: "84532",
    numericId: 84532,
    name: "Base Sepolia",
    key: "base-sepolia",
    type: "evm",
    nativeCurrency: { name: "Sepolia Ether", symbol: "ETH", decimals: 18 },
    rpcUrl: "https://sepolia.base.org",
    explorerUrl: "https://sepolia.basescan.org",
    supportedFeatures: ["bridge", "rpc-proxy", "wallet-balance"],
  },
  {
    chainId: "421614",
    numericId: 421614,
    name: "Arbitrum Sepolia",
    key: "arbitrum-sepolia",
    type: "evm",
    nativeCurrency: { name: "Sepolia Ether", symbol: "ETH", decimals: 18 },
    rpcUrl: "https://sepolia-rollup.arbitrum.io/rpc",
    explorerUrl: "https://sepolia.arbiscan.io",
    supportedFeatures: ["bridge", "rpc-proxy", "wallet-balance"],
  },
  {
    chainId: "11155420",
    numericId: 11155420,
    name: "Optimism Sepolia",
    key: "optimism-sepolia",
    type: "evm",
    nativeCurrency: { name: "Sepolia Ether", symbol: "ETH", decimals: 18 },
    rpcUrl: "https://sepolia.optimism.io",
    explorerUrl: "https://sepolia-optimism.etherscan.io",
    supportedFeatures: ["bridge", "rpc-proxy", "wallet-balance"],
  },
  {
    chainId: "43113",
    numericId: 43113,
    name: "Avalanche Fuji",
    key: "avalanche-fuji",
    type: "evm",
    nativeCurrency: { name: "Avalanche", symbol: "AVAX", decimals: 18 },
    rpcUrl: "https://api.avax-test.network/ext/bc/C/rpc",
    explorerUrl: "https://testnet.snowtrace.io",
    supportedFeatures: ["bridge", "rpc-proxy", "wallet-balance"],
  },
  {
    chainId: "11155111",
    numericId: 11155111,
    name: "Ethereum Sepolia",
    key: "ethereum-sepolia",
    type: "evm",
    nativeCurrency: { name: "Sepolia Ether", symbol: "ETH", decimals: 18 },
    rpcUrl: "https://ethereum-sepolia-rpc.publicnode.com",
    explorerUrl: "https://sepolia.etherscan.io",
    supportedFeatures: ["bridge", "rpc-proxy", "wallet-balance"],
  },
  {
    chainId: "59141",
    numericId: 59141,
    name: "Linea Sepolia",
    key: "linea-sepolia",
    type: "evm",
    nativeCurrency: { name: "Sepolia Ether", symbol: "ETH", decimals: 18 },
    rpcUrl: "https://rpc.sepolia.linea.build",
    explorerUrl: "https://sepolia.lineascan.build",
    supportedFeatures: ["bridge", "rpc-proxy", "wallet-balance"],
  },
  {
    chainId: "80002",
    numericId: 80002,
    name: "Polygon Amoy",
    key: "polygon-amoy",
    type: "evm",
    nativeCurrency: { name: "Polygon", symbol: "POL", decimals: 18 },
    rpcUrl: "https://rpc-amoy.polygon.technology",
    explorerUrl: "https://amoy.polygonscan.com",
    supportedFeatures: ["bridge", "rpc-proxy", "wallet-balance"],
  },
  {
    chainId: "14601",
    numericId: 14601,
    name: "Sonic Testnet",
    key: "sonic-testnet",
    type: "evm",
    nativeCurrency: { name: "Sonic", symbol: "S", decimals: 18 },
    rpcUrl: "https://rpc.testnet.soniclabs.com",
    explorerUrl: "https://testnet.sonicscan.org",
    supportedFeatures: ["bridge", "rpc-proxy", "wallet-balance"],
  },
  {
    chainId: "1301",
    numericId: 1301,
    name: "Unichain Sepolia",
    key: "unichain-sepolia",
    type: "evm",
    nativeCurrency: { name: "Sepolia Ether", symbol: "ETH", decimals: 18 },
    rpcUrl: "https://sepolia.unichain.org",
    explorerUrl: "https://sepolia.uniscan.xyz",
    supportedFeatures: ["bridge", "rpc-proxy", "wallet-balance"],
  },
  {
    chainId: "solana",
    numericId: null,
    name: "Solana Devnet",
    key: "solana",
    type: "solana",
    nativeCurrency: { name: "SOL", symbol: "SOL", decimals: 9 },
    rpcUrl: "https://api.devnet.solana.com",
    explorerUrl: "https://explorer.solana.com/?cluster=devnet",
    supportedFeatures: ["bridge", "rpc-proxy", "wallet-balance"],
  },
  {
    chainId: "5042",
    numericId: 5042,
    name: "Arc",
    key: "arc",
    type: "evm",
    nativeCurrency: { name: "USD Coin", symbol: "USDC", decimals: 18 },
    rpcUrl: "https://rpc.arc-scan.org",
    explorerUrl: "https://arc-scan.org",
    supportedFeatures: ["bridge", "rpc-proxy", "wallet-balance"],
  },
  {
    chainId: "1",
    numericId: 1,
    name: "Ethereum",
    key: "ethereum",
    type: "evm",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrl: "https://ethereum.publicnode.com",
    explorerUrl: "https://etherscan.io",
    supportedFeatures: ["bridge", "rpc-proxy", "wallet-balance"],
  },
  {
    chainId: "8453",
    numericId: 8453,
    name: "Base",
    key: "base",
    type: "evm",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrl: "https://mainnet.base.org",
    explorerUrl: "https://basescan.org",
    supportedFeatures: ["bridge", "rpc-proxy", "wallet-balance"],
  },
  {
    chainId: "10",
    numericId: 10,
    name: "Optimism",
    key: "optimism",
    type: "evm",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrl: "https://mainnet.optimism.io",
    explorerUrl: "https://optimistic.etherscan.io",
    supportedFeatures: ["bridge", "rpc-proxy", "wallet-balance"],
  },
  {
    chainId: "42161",
    numericId: 42161,
    name: "Arbitrum",
    key: "arbitrum",
    type: "evm",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrl: "https://arb1.arbitrum.io/rpc",
    explorerUrl: "https://arbiscan.io",
    supportedFeatures: ["bridge", "rpc-proxy", "wallet-balance"],
  },
  {
    chainId: "137",
    numericId: 137,
    name: "Polygon",
    key: "polygon",
    type: "evm",
    nativeCurrency: { name: "POL", symbol: "POL", decimals: 18 },
    rpcUrl: "https://polygon-rpc.com",
    explorerUrl: "https://polygonscan.com",
    supportedFeatures: ["bridge", "rpc-proxy", "wallet-balance"],
  },
  {
    chainId: "43114",
    numericId: 43114,
    name: "Avalanche",
    key: "avalanche",
    type: "evm",
    nativeCurrency: { name: "Avalanche", symbol: "AVAX", decimals: 18 },
    rpcUrl: "https://api.avax.network/ext/bc/C/rpc",
    explorerUrl: "https://snowtrace.io",
    supportedFeatures: ["bridge", "rpc-proxy", "wallet-balance"],
  },
  {
    chainId: "59144",
    numericId: 59144,
    name: "Linea",
    key: "linea",
    type: "evm",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrl: "https://rpc.linea.build",
    explorerUrl: "https://lineascan.build",
    supportedFeatures: ["bridge", "rpc-proxy", "wallet-balance"],
  },
  {
    chainId: "146",
    numericId: 146,
    name: "Sonic",
    key: "sonic",
    type: "evm",
    nativeCurrency: { name: "Sonic", symbol: "S", decimals: 18 },
    rpcUrl: "https://rpc.soniclabs.com",
    explorerUrl: "https://sonicscan.org",
    supportedFeatures: ["bridge", "rpc-proxy", "wallet-balance"],
  },
  {
    chainId: "130",
    numericId: 130,
    name: "Unichain",
    key: "unichain",
    type: "evm",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrl: "https://mainnet.unichain.org",
    explorerUrl: "https://uniscan.xyz",
    supportedFeatures: ["bridge", "rpc-proxy", "wallet-balance"],
  },
  {
    chainId: "solana-mainnet",
    numericId: null,
    name: "Solana",
    key: "solana-mainnet",
    type: "solana",
    nativeCurrency: { name: "SOL", symbol: "SOL", decimals: 9 },
    rpcUrl: "https://api.mainnet-beta.solana.com",
    explorerUrl: "https://explorer.solana.com",
    supportedFeatures: ["bridge", "rpc-proxy", "wallet-balance"],
  },
];

export async function getChainsResponse() {
  return NextResponse.json({
    success: true,
    data: SUPPORTED_CHAINS,
  });
}

export const GET = withFrontendOriginGate(async (_request: NextRequest) =>
  getChainsResponse(),
);
